### ISSUE TITLE
Problem with siteIdentifier

### ISSUE THREAD

**Issue by devmes** [undkonsorten/extbase-cli-aware-configuration-manager#1]
I have tried to overwrite the SiteIdentifier in my extension in Configuration/Services.yaml. However, this configuration is not accepted and I get the following error message when calling it in the CLI:
‘There is not site identifier provided. Please provide one via Service.yaml or Service.php. Read README.md for more help’

My Service.yaml file looks like this:

```
services:
  TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface:
    alias: 'Undkonsorten\ExtbaseCliAwareConfigurationManager\Configuration\CliAwareConfigurationManager'
    public: true

  Undkonsorten\ExtbaseCliAwareConfigurationManager\Configuration\CommandLineInterfaceConfigurationManager:
    arguments:
      $siteIdentifier: 'mysite'
```

Do you have any idea what the problem could be?
